"""add phone and address to user model

Revision ID: 05adac1e71a3
Revises: 9e790993bce6
Create Date: 2026-06-18 20:22:58.906060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05adac1e71a3'
down_revision = '9e790993bce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
